Repository cjavad/dare, pull requests merged in 2022-09, with the labels that each got.

#11 Implements a test for TokenStream::parse
  src/token_stream.rs
Labels: test

#21 Implemented Assignment and TruthValues to lexer and parser. Renamed XOR operation from + to ^.
  README.md
  src/ast.rs
  src/parser.rs
  src/token.rs
  src/token_stream.rs
Labels: enhancement

#23 Initial intepreter with variable support and tests
  src/ast.rs
  src/interpreter.rs
  src/lib.rs
  src/parser.rs
Labels: enhancement, test

#24 Refactor parsing of TokenKind::TruthValue
  src/token_stream.rs
Labels: refactor

#25 Impl tableau
  src/interpreter.rs
  src/lib.rs
  src/parser.rs
  src/tableau.rs
  src/token.rs
  src/token_stream.rs
Labels: NO SQUASH

#27 Impl latex writer
  Cargo.toml
  src/latex_writer.rs
  src/lib.rs
  src/tableau.rs
  src/writer.rs
Labels: enhancement, NO SQUASH

#32 Add description for solve subcommand
  dare-cli/b
  dare-cli/src/main.rs
  dare-cli/v
Labels: documentation

#33 Adds path option to CLI
  dare-cli/src/main.rs
Labels: enhancement

#34 Implement completion subcommand
  Cargo.lock
  dare-cli/Cargo.toml
  dare-cli/src/build.rs
  dare-cli/src/clipboard.rs
  dare-cli/src/command.rs
  dare-cli/src/main.rs
Labels: enhancement

#35 Refractored and patched windows powershell autocomplete script installation for cli.
  .gitignore
  dare-cli/src/build.rs
  dare-cli/src/command.rs
  dare-cli/src/main.rs
Labels: bug, enhancement

#36 Fix compile error on linux
  dare-cli/src/main.rs
Labels: bug

#37 Fix solver
  src/solve.rs
Labels: bug

#39 Fix height
  src/latex_writer.rs
Labels: bug

#40 Implement expectation ids
  src/ast.rs
  src/latex_writer.rs
  src/solve.rs
  src/tableau.rs
Labels: enhancement
